(function(){
  const Zip=self.SiteForgeZip;

  function ensure(project,files){
    if(!files['package.json'])files['package.json']=JSON.stringify({name:project.name||'siteforge-app',version:project.version||'1.0.0',private:true,scripts:{dev:'next dev',build:'next build',start:'next start'},dependencies:{next:'14.0.0',react:'18.2.0','react-dom':'18.2.0'},devDependencies:{tailwindcss:'^3.4.0',autoprefixer:'^10.4.0',postcss:'^8.4.0'}},null,2);
    if(!files['next.config.js'])files['next.config.js']="module.exports={};\n";
    if(!files['tailwind.config.cjs'])files['tailwind.config.cjs']="module.exports={content:['./app/**/*.{js,jsx,ts,tsx}','./pages/**/*.{js,jsx,ts,tsx}','./components/**/*.{js,jsx,ts,tsx}'],theme:{extend:{}},plugins:[]};\n";
    if(!files['postcss.config.cjs'])files['postcss.config.cjs']="module.exports={plugins:{tailwindcss:{},autoprefixer:{}}};\n";
    if(!files['app/globals.css'])files['app/globals.css']='@tailwind base;@tailwind components;@tailwind utilities;';
    const hasEntry=Object.keys(files).some(p=>/^app\/page\.(js|jsx|ts|tsx)$/.test(p)||/^pages\/index\.(js|jsx|ts|tsx)$/.test(p));
    if(!hasEntry)files['app/page.jsx']="import './globals.css';export default function Page(){return(<main className='min-h-screen flex items-center justify-center bg-slate-950 text-slate-50'><div className='max-w-xl mx-auto p-6 rounded-xl bg-slate-900 border border-slate-800'><h1 className='text-3xl font-bold mb-2'>SiteForge AI</h1><p className='text-slate-300 text-sm'>Generated from a website snapshot. Start customizing this page.</p></div></main>);}\n";
    if(!files['.eslintrc.json'])files['.eslintrc.json']=JSON.stringify({extends:['next','next/core-web-vitals']},null,2);
    if(!files['.prettierrc'])files['.prettierrc']=JSON.stringify({singleQuote:true,trailingComma:'none'},null,2);
    if(!files['README.md'])files['README.md']="# "+(project.name||'SiteForge Static Copy')+"\n\n## About\n\nThis is a static Next.js 14 export of a website, generated by **SiteForge**.\n\nThe project includes:\n- **Original HTML structure** from the scraped page\n- **Original CSS styling** (inline + external stylesheets)\n- **Downloaded assets** (images, backgrounds, etc.)\n- **Dark mode support** (if the original site had it)\n\n## Getting Started\n\n### Prerequisites\n- Node.js 18+ and npm\n\n### Installation\n\n```bash\nnpm install\n```\n\n### Development\n\n```bash\nnpm run dev\n```\n\nOpen [http://localhost:3000](http://localhost:3000) to view the site.\n\n### Production Build\n\n```bash\nnpm run build\nnpm run start\n```\n\n## Customization\n\nYou can customize the exported project:\n\n- **Styling**: Edit `public/legacy.css` to adjust the original styles\n- **Layout**: Edit `app/layout.jsx` to modify the page structure\n- **Add Components**: Create new React components in `app/` directory\n- **Tailwind CSS**: Customize `tailwind.config.cjs` for additional styling\n\n## Deployment\n\nDeploy to Vercel:\n\n```bash\nnpm install -g vercel\nvercel\n```\n\nOr deploy to any Next.js-compatible hosting (Netlify, AWS, etc.).\n\n## Notes\n\n- JavaScript from the original site is not included (for security and portability)\n- Interactive features that relied on JS will need to be re-implemented\n- Some external resources may not load if they have CORS restrictions\n\n---\n\nGenerated by [SiteForge](https://github.com/yourusername/siteforge)\n";
  }

  function dataUriToBytes(uri){const i=uri.indexOf(',');if(i===-1)return null;const b64=uri.slice(i+1);try{const bin=atob(b64),out=new Uint8Array(bin.length);for(let j=0;j<bin.length;j++)out[j]=bin.charCodeAt(j);return out;}catch(_){return null;}}

  async function buildProjectZip(project){
    const files={};
    if(Array.isArray(project.files))project.files.forEach(f=>{files[f.path]=f.content;});
    ensure(project,files);
    if(Array.isArray(project.assets))for(const a of project.assets){if(a.dataUri){const b=dataUriToBytes(a.dataUri);if(b)files[a.path]=b;}}
    return Zip.createZipBlobFromFiles(files);
  }

  function extractComponents(html){
    const components={};
    const patterns=[
      {name:'Header',selector:'header, [role="banner"], .header, .navbar, nav'},
      {name:'Footer',selector:'footer, [role="contentinfo"], .footer'},
      {name:'Card',selector:'.card, [class*="card"], article, .post'},
      {name:'Button',selector:'button, [role="button"], .btn'},
      {name:'Form',selector:'form, [role="form"]'},
      {name:'Modal',selector:'[role="dialog"], .modal, .popup'},
      {name:'Sidebar',selector:'aside, [role="complementary"], .sidebar'}
    ];

    const parser=typeof DOMParser!=='undefined'?new DOMParser():null;
    if(!parser)return components;

    try{
      const doc=parser.parseFromString(html,'text/html');
      for(const p of patterns){
        const els=doc.querySelectorAll(p.selector);
        if(els.length>0){
          const el=els[0];
          const code=el.outerHTML.slice(0,500);
          components[p.name]={
            count:els.length,
            sample:code,
            selector:p.selector
          };
        }
      }
    }catch(_){ }
    return components;
  }

  function escapeJsString(value){
    return String(value||'').replace(/\\/g,'\\\\').replace(/\r/g,'\\r').replace(/\n/g,'\\n').replace(/"/g,'\\"');
  }

  function escapeTemplateLiteral(value){
    return String(value||'').replace(/\\/g,'\\\\').replace(/`/g,'\\`').replace(/\$\{/g,'\\${');
  }

  function stripDangerousHtml(html){
    return String(html||'')
      .replace(/<script[\s\S]*?<\/script>/gi,'')
      .replace(/on\w+\s*=\s*["'][^"']*["']/gi,'');
  }

  function extractBodySection(html){
    const fullHtml=String(html||'');
    let bodyHtml=fullHtml;
    let bodyClass='';
    const bodyMatch=fullHtml.match(/<body([^>]*)>([\s\S]*?)<\/body>/i);
    if(bodyMatch){
      const attrs=bodyMatch[1]||'';
      bodyHtml=bodyMatch[2]||'';
      const classMatch=attrs.match(/class=["']([^"']*)["']/i);
      if(classMatch)bodyClass=classMatch[1];
    }
    return {bodyHtml,bodyClass};
  }

  function rewriteAssetUrls(text,urlMap){
    let output=String(text||'');
    Object.entries(urlMap||{}).forEach(([origUrl,newPath])=>{
      if(!origUrl||!newPath)return;
      const safe=origUrl.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
      output=output.replace(new RegExp(safe,'g'),'/' + newPath);
    });
    return output;
  }

  function sanitizeRouteSegment(segment){
    let decoded=segment||'';
    try{decoded=decodeURIComponent(decoded);}catch(_){ }
    return decoded
      .trim()
      .replace(/[^a-zA-Z0-9_-]+/g,'-')
      .replace(/-+/g,'-')
      .replace(/^-|-$/g,'')||'page';
  }

  function routePathFromUrl(url,index){
    try{
      const parsed=new URL(url,'https://siteforge.local');
      let pathname=parsed.pathname||'/';
      pathname=pathname.replace(/\/index\.html?$/i,'/');
      pathname=pathname.replace(/\.html?$/i,'');
      if(!pathname||pathname==='/')return '';
      const segments=pathname.split('/').filter(Boolean).map(sanitizeRouteSegment);
      return segments.join('/');
    }catch(_){
      return index===0?'':'page-'+(index+1);
    }
  }

  function buildPageModule(page){
    const title=escapeJsString(page.title||'SiteForge Page');
    const description=page.description?`, description: "${escapeJsString(page.description)}"`:'';
    const html=escapeTemplateLiteral(stripDangerousHtml(page.html||''));
    const className=escapeJsString(['siteforge-page',page.bodyClass||''].filter(Boolean).join(' ').trim());
    return "export const metadata={title: \""+title+"\""+description+"};\n"+
      "export default function Page(){\n"+
      "  return (\n"+
      "    <div className=\""+className+"\" dangerouslySetInnerHTML={{ __html: `"+html+"` }} />\n"+
      "  );\n"+
      "}\n";
  }

  function buildLayoutModule(snapshot){
    const metaTags=(snapshot&&snapshot.meta)||{};
    const name=snapshot&&snapshot.title?snapshot.title:'SiteForge Static Copy';
    const description=metaTags['description']||metaTags['og:description']||'A website exported by SiteForge.';
    const ogImage=metaTags['og:image']||'';
    const lang=(snapshot&&snapshot.lang)||'en';
    const bodyClass=['siteforge-original',snapshot&&snapshot.bodyClass?snapshot.bodyClass:''].filter(Boolean).join(' ').trim();

    return "import './globals.css';\n"+
      "export const metadata={\n"+
      "  title: \""+escapeJsString(name)+"\",\n"+
      "  description: \""+escapeJsString(description.slice(0,160))+"\",\n"+
      "  openGraph: {\n"+
      "    title: \""+escapeJsString(name)+"\",\n"+
      "    description: \""+escapeJsString(description.slice(0,160))+"\",\n"+
      "    type: 'website',\n"+
      "    url: '/',\n"+
      (ogImage?"    images: [\""+escapeJsString(ogImage)+"\"],\n":'')+
      "  },\n"+
      "  robots: 'index, follow',\n"+
      "};\n"+
      "export default function RootLayout({children}){\n"+
      "  return (\n"+
      "    <html lang=\""+escapeJsString(lang||'en')+"\">\n"+
      "      <head>\n"+
      "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"+
      "        <meta name=\"theme-color\" content=\"#ffffff\" />\n"+
      "        <link rel=\"icon\" href=\"/favicon.ico\" />\n"+
      "        <link rel=\"stylesheet\" href=\"/legacy.css\" />\n"+
      "      </head>\n"+
      "      <body className=\""+escapeJsString(bodyClass)+"\">{children}</body>\n"+
      "    </html>\n"+
      "  );\n"+
      "}\n";
  }

  function buildRouteGuide(pageRoutes){
    const routes=pageRoutes||[];
    if(!routes.length)return '';
    return '# Page Routes\n\n'+
      'This export includes the following Next.js routes:\n\n'+
      routes.map(page=>{
        const route=page.route?'/'+page.route.replace(/^\/+/, ''):'/';
        return '- `'+route+'` -> `'+(page.url||'')+'`';
      }).join('\n')+
      '\n\nInternal links were preserved using the source site path structure.\n';
  }

  function buildSitemap(routePaths){
    const today=new Date().toISOString().split('T')[0];
    const seen=new Set();
    const urls=[];
    (routePaths||[]).forEach(route=>{
      const normalized=route?String(route).replace(/^\/+/, ''):'';
      if(seen.has(normalized))return;
      seen.add(normalized);
      urls.push(normalized?'https://yourdomain.com/'+normalized:'https://yourdomain.com/');
    });
    return '<?xml version="1.0" encoding="UTF-8"?>\n'+
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+
      urls.map((loc,index)=>(
        '  <url>\n'+
        '    <loc>'+loc+'</loc>\n'+
        '    <lastmod>'+today+'</lastmod>\n'+
        '    <changefreq>weekly</changefreq>\n'+
        '    <priority>'+(index===0?'1.0':'0.7')+'</priority>\n'+
        '  </url>'
      )).join('\n')+
      '\n</urlset>\n';
  }

  async function buildStaticCopyZip(snapshot){
    snapshot=snapshot||{};
    const name=snapshot.title||'siteforge-static-copy';
    const project={name,version:'1.0.0',packageManager:'npm',files:[],assets:[]};
    const files={};
    const urlMap=snapshot.assetUrlMap||{};

    const fullHtml=String(snapshot.fullHtml||'');
    const rootBody=extractBodySection(fullHtml);
    const rootBodyHtml=rewriteAssetUrls(stripDangerousHtml(rootBody.bodyHtml),urlMap);
    const rootBodyClass=snapshot.bodyClass||rootBody.bodyClass||'';
    const rootLang=snapshot.lang||'en';

    files['app/page.jsx']=buildPageModule({
      title:name,
      html:rootBodyHtml,
      bodyClass:rootBodyClass
    });

    const legacyParts=[];
    const inline=snapshot.inlineStyles||'';
    if(inline){
      legacyParts.push('/* Inline styles from source page */');
      let cssText=inline.replace(/<[^>]*>/g,'').replace(/<!--[\s\S]*?-->/g,'');
      cssText=rewriteAssetUrls(cssText,urlMap);
      legacyParts.push(cssText);
    }
    const external=snapshot.externalStyles||{};
    Object.keys(external).forEach(nameKey=>{
      const css=external[nameKey];
      if(css){
        legacyParts.push('/* '+nameKey+' */');
        let cssText=css.replace(/<[^>]*>/g,'').replace(/<!--[\s\S]*?-->/g,'');
        cssText=rewriteAssetUrls(cssText,urlMap);
        legacyParts.push(cssText);
      }
    });
    if(legacyParts.length)files['public/legacy.css']=legacyParts.join('\n');

    const metaTags=snapshot.meta||{};
    const description=metaTags['description']||metaTags['og:description']||'A website exported by SiteForge.';
    const ogImage=metaTags['og:image']||'';

    files['app/layout.jsx']=buildLayoutModule({
      title:name,
      description,
      ogImage,
      lang:rootLang,
      bodyClass:rootBodyClass
    });

    files['app/globals.css']=[
      '@tailwind base;',
      '@tailwind components;',
      '@tailwind utilities;',
      '',
      '.siteforge-original, .siteforge-page { min-height: 100vh; }'
    ].join('\n');

    const crawledPages=Array.isArray(snapshot.pages)?snapshot.pages:[];
    const pageRoutes=[{route:'',url:snapshot.url||'https://yourdomain.com/',title:name}];
    const routeEntries=[];
    const seenRoutes=new Set(['']);

    crawledPages.forEach((page,index)=>{
      const route=routePathFromUrl(page.url,index);
      if(!route||seenRoutes.has(route))return;
      seenRoutes.add(route);
      routeEntries.push({
        route,
        title:page.title||route.split('/').pop()||'Page',
        html:rewriteAssetUrls(stripDangerousHtml(extractBodySection(String(page.html||'')).bodyHtml),urlMap),
        bodyClass:page.bodyClass||extractBodySection(String(page.html||'')).bodyClass||'',
        url:page.url||''
      });
      pageRoutes.push({route,url:page.url||'',title:page.title||route});
    });

    routeEntries.forEach(page=>{
      files['app/'+page.route+'/page.jsx']=buildPageModule(page);
    });

    if(routeEntries.length){
      files['PAGES.md']=buildRouteGuide(pageRoutes);
    }

    files['public/sitemap.xml']=buildSitemap(pageRoutes.map(page=>page.route));
    files['public/robots.txt']='User-agent: *\n'+
      'Allow: /\n'+
      'Sitemap: https://yourdomain.com/sitemap.xml\n';

    const components=extractComponents(fullHtml);
    const componentsDocs='# Component Guide\n\n'+
      'This page was analyzed and the following reusable components were detected:\n\n'+
      Object.entries(components).map(([componentName,info])=>
        '## '+componentName+'\n\n'+
        '- **Found**: '+info.count+' instance(s)\n'+
        '- **Selector**: `'+info.selector+'`\n'+
        '- **Sample HTML**:\n```html\n'+info.sample+'\n```\n'
      ).join('\n')+
      '\n## How to Use\n\n'+
      'You can extract these patterns into reusable React components in `app/components/`:\n\n'+
      '```jsx\n'+
      '// app/components/Header.jsx\n'+
      'export default function Header() {\n'+
      '  return (\n'+
      '    <header>\n'+
      '      {/* Your header content here */}\n'+
      '    </header>\n'+
      '  );\n'+
      '}\n'+
      '```\n';
    files['COMPONENTS.md']=componentsDocs;

    const assetMap=snapshot.assets||{};
    const assets=[];
    Object.keys(assetMap).forEach(fileName=>{
      const uri=assetMap[fileName];
      if(typeof uri==='string'&&uri.startsWith('data:')){
        assets.push({path:'public/'+fileName,dataUri:uri});
      }
    });
    project.assets=assets;

    Object.keys(files).forEach(p=>{project.files.push({path:p,content:files[p]});});
    const blob=await buildProjectZip(project);
    return{blob,project};
  }

  self.SiteForgeBuilder={buildProjectZip,buildStaticCopyZip};
})();
(function(){
  const Zip=self.SiteForgeZip;

  function ensure(project,files){
    if(!files['package.json'])files['package.json']=JSON.stringify({name:project.name||'siteforge-app',version:project.version||'1.0.0',private:true,scripts:{dev:'next dev',build:'next build',start:'next start'},dependencies:{next:'14.0.0',react:'18.2.0','react-dom':'18.2.0'},devDependencies:{tailwindcss:'^3.4.0',autoprefixer:'^10.4.0',postcss:'^8.4.0'}},null,2);
    if(!files['next.config.js'])files['next.config.js']="module.exports={};\n";
    if(!files['tailwind.config.cjs'])files['tailwind.config.cjs']="module.exports={content:['./app/**/*.{js,jsx,ts,tsx}','./pages/**/*.{js,jsx,ts,tsx}','./components/**/*.{js,jsx,ts,tsx}'],theme:{extend:{}},plugins:[]};\n";
    if(!files['postcss.config.cjs'])files['postcss.config.cjs']="module.exports={plugins:{tailwindcss:{},autoprefixer:{}}};\n";
    if(!files['app/globals.css'])files['app/globals.css']='@tailwind base;@tailwind components;@tailwind utilities;';
    const hasEntry=Object.keys(files).some(p=>/^app\/page\.(js|jsx|ts|tsx)$/.test(p)||/^pages\/index\.(js|jsx|ts|tsx)$/.test(p));
    if(!hasEntry)files['app/page.jsx']="import './globals.css';export default function Page(){return(<main className='min-h-screen flex items-center justify-center bg-slate-950 text-slate-50'><div className='max-w-xl mx-auto p-6 rounded-xl bg-slate-900 border border-slate-800'><h1 className='text-3xl font-bold mb-2'>SiteForge AI</h1><p className='text-slate-300 text-sm'>Generated from a website snapshot. Start customizing this page.</p></div></main>);}\n";
    if(!files['.eslintrc.json'])files['.eslintrc.json']=JSON.stringify({extends:['next','next/core-web-vitals']},null,2);
    if(!files['.prettierrc'])files['.prettierrc']=JSON.stringify({singleQuote:true,trailingComma:'none'},null,2);
    if(!files['README.md'])files['README.md']="# "+(project.name||'SiteForge Static Copy')+"\n\n## About\n\nThis is a static Next.js 14 export of a website, generated by **SiteForge**.\n\nThe project includes:\n- **Original HTML structure** from the scraped page\n- **Original CSS styling** (inline + external stylesheets)\n- **Downloaded assets** (images, backgrounds, etc.)\n- **Dark mode support** (if the original site had it)\n\n## Getting Started\n\n### Prerequisites\n- Node.js 18+ and npm\n\n### Installation\n\n```bash\nnpm install\n```\n\n### Development\n\n```bash\nnpm run dev\n```\n\nOpen [http://localhost:3000](http://localhost:3000) to view the site.\n\n### Production Build\n\n```bash\nnpm run build\nnpm run start\n```\n\n## Customization\n\nYou can customize the exported project:\n\n- **Styling**: Edit `public/legacy.css` to adjust the original styles\n- **Layout**: Edit `app/layout.jsx` to modify the page structure\n- **Add Components**: Create new React components in `app/` directory\n- **Tailwind CSS**: Customize `tailwind.config.cjs` for additional styling\n\n## Deployment\n\nDeploy to Vercel:\n\n```bash\nnpm install -g vercel\nvercel\n```\n\nOr deploy to any Next.js-compatible hosting (Netlify, AWS, etc.).\n\n## Notes\n\n- JavaScript from the original site is not included (for security and portability)\n- Interactive features that relied on JS will need to be re-implemented\n- Some external resources may not load if they have CORS restrictions\n\n---\n\nGenerated by [SiteForge](https://github.com/yourusername/siteforge)\n";
  }

  function dataUriToBytes(uri){const i=uri.indexOf(',');if(i===-1)return null;const b64=uri.slice(i+1);try{const bin=atob(b64),out=new Uint8Array(bin.length);for(let j=0;j<bin.length;j++)out[j]=bin.charCodeAt(j);return out;}catch(_){return null;}}

  async function buildProjectZip(project){
    const files={};
    if(Array.isArray(project.files))project.files.forEach(f=>{files[f.path]=f.content;});
    ensure(project,files);
    if(Array.isArray(project.assets))for(const a of project.assets){if(a.dataUri){const b=dataUriToBytes(a.dataUri);if(b)files[a.path]=b;}}
    return Zip.createZipBlobFromFiles(files);
  }

  function extractComponents(html){
    const components={};
    const patterns=[
      {name:'Header',selector:'header, [role="banner"], .header, .navbar, nav'},
      {name:'Footer',selector:'footer, [role="contentinfo"], .footer'},
      {name:'Card',selector:'.card, [class*="card"], article, .post'},
      {name:'Button',selector:'button, [role="button"], .btn'},
      {name:'Form',selector:'form, [role="form"]'},
      {name:'Modal',selector:'[role="dialog"], .modal, .popup'},
      {name:'Sidebar',selector:'aside, [role="complementary"], .sidebar'}
    ];

    const parser=typeof DOMParser!=='undefined'?new DOMParser():null;
    if(!parser)return components;

    try{
      const doc=parser.parseFromString(html,'text/html');
      for(const p of patterns){
        const els=doc.querySelectorAll(p.selector);
        if(els.length>0){
          const el=els[0];
          const code=el.outerHTML.slice(0,500);
          components[p.name]={
            count:els.length,
            sample:code,
            selector:p.selector
          };
        }
      }
    }catch(_){ }
    return components;
  }

  function escapeJsString(value){
    return String(value||'').replace(/\\/g,'\\\\').replace(/\r/g,'\\r').replace(/\n/g,'\\n').replace(/"/g,'\\"');
  }

  function escapeTemplateLiteral(value){
    return String(value||'').replace(/\\/g,'\\\\').replace(/`/g,'\\`').replace(/\$\{/g,'\\${');
  }

  function stripDangerousHtml(html){
    return String(html||'').replace(/<script[\s\S]*?<\/script>/gi,'').replace(/on\w+\s*=\s*["'][^"']*["']/gi,'');
  }

  function extractBodySection(html){
    const fullHtml=String(html||'');
    let bodyHtml=fullHtml;
    let bodyClass='';
    const bodyMatch=fullHtml.match(/<body([^>]*)>([\s\S]*?)<\/body>/i);
    if(bodyMatch){
      const attrs=bodyMatch[1]||'';
      bodyHtml=bodyMatch[2]||'';
      const classMatch=attrs.match(/class=["']([^"']*)["']/i);
      if(classMatch)bodyClass=classMatch[1];
    }
    return{bodyHtml,bodyClass};
  }

  function rewriteAssetUrls(text,urlMap){
    let output=String(text||'');
    Object.entries(urlMap||{}).forEach(([origUrl,newPath])=>{
      if(!origUrl||!newPath)return;
      const safe=origUrl.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
      output=output.replace(new RegExp(safe,'g'),'/' + newPath);
    });
    return output;
  }

  function sanitizeRouteSegment(segment){
    let decoded=segment||'';
    try{decoded=decodeURIComponent(decoded);}catch(_){ }
    const cleaned=decoded.trim().replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');
    return cleaned||'page';
  }

  function routePathFromUrl(url,index){
    try{
      const parsed=new URL(url,'https://siteforge.local');
      let pathname=parsed.pathname||'/';
      pathname=pathname.replace(/\/index\.html?$/i,'/');
      pathname=pathname.replace(/\.html?$/i,'');
      if(!pathname||pathname==='/')return '';
      const segments=pathname.split('/').filter(Boolean).map(sanitizeRouteSegment);
      return segments.join('/');
    }catch(_){
      return index===0?'':'page-'+(index+1);
    }
  }

  function buildPageModule(page){
    const title=escapeJsString(page.title||'SiteForge Page');
    const html=escapeTemplateLiteral(stripDangerousHtml(page.html||''));
    const className=escapeJsString(['siteforge-page',page.bodyClass||''].filter(Boolean).join(' ').trim());
    const description=page.description?(', description: "'+escapeJsString(page.description)+'"'):'',
      metadata='export const metadata={title: "'+title+'"'+description+'};\n';
    return metadata+
      'export default function Page(){\n'+
      '  return (\n'+
      '    <div className="'+className+'" dangerouslySetInnerHTML={{ __html: `'+html+'` }} />\n'+
      '  );\n'+
      '}\n';
  }

  function buildLayoutModule(snapshot){
    const metaTags=(snapshot&&snapshot.meta)||{};
    const name=(snapshot&&snapshot.title)||'SiteForge Static Copy';
    const description=metaTags['description']||metaTags['og:description']||'A website exported by SiteForge.';
    const ogImage=metaTags['og:image']||'';
    const lang=(snapshot&&snapshot.lang)||'en';
    const bodyClass=['siteforge-original',snapshot&&snapshot.bodyClass?snapshot.bodyClass:''].filter(Boolean).join(' ').trim();
    return "import './globals.css';\n"+
      'export const metadata={\n'+
      '  title: "'+escapeJsString(name)+'",\n'+
      '  description: "'+escapeJsString(description.slice(0,160))+'",\n'+
      '  openGraph: {\n'+
      '    title: "'+escapeJsString(name)+'",\n'+
      '    description: "'+escapeJsString(description.slice(0,160))+'",\n'+
      "    type: 'website',\n"+
      "    url: '/',\n"+
      (ogImage?'    images: ["'+escapeJsString(ogImage)+'"],\n':'')+
      '  },\n'+
      "  robots: 'index, follow',\n"+
      '};\n'+
      'export default function RootLayout({children}){\n'+
      '  return (\n'+
      '    <html lang="'+escapeJsString(lang)+'">\n'+
      '      <head>\n'+
      '        <meta name="viewport" content="width=device-width, initial-scale=1" />\n'+
      '        <meta name="theme-color" content="#ffffff" />\n'+
      '        <link rel="icon" href="/favicon.ico" />\n'+
      '        <link rel="stylesheet" href="/legacy.css" />\n'+
      '      </head>\n'+
      '      <body className="'+escapeJsString(bodyClass)+'">{children}</body>\n'+
      '    </html>\n'+
      '  );\n'+
      '}\n';
  }

  function buildRouteGuide(pageRoutes){
    const routes=Array.isArray(pageRoutes)?pageRoutes:[];
    if(!routes.length)return '';
    return '# Page Routes\n\n'+
      'This export includes the following Next.js routes:\n\n'+
      routes.map(page=>{
        const route=page.route?'/'+String(page.route).replace(/^\/+/,''):'/';
        return '- `'+route+'` -> `'+(page.url||'')+'`';
      }).join('\n')+
      '\n\nInternal links were preserved using the source site path structure.\n';
  }

  function buildSitemap(routePaths){
    const today=new Date().toISOString().split('T')[0];
    const seen=new Set();
    const urls=[];
    (routePaths||[]).forEach(route=>{
      const normalized=route?String(route).replace(/^\/+/,''):'';
      if(seen.has(normalized))return;
      seen.add(normalized);
      urls.push(normalized?'https://yourdomain.com/'+normalized:'https://yourdomain.com/');
    });
    return '<?xml version="1.0" encoding="UTF-8"?>\n'+
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+
      urls.map((loc,index)=>
        '  <url>\n'+
        '    <loc>'+loc+'</loc>\n'+
        '    <lastmod>'+today+'</lastmod>\n'+
        '    <changefreq>weekly</changefreq>\n'+
        '    <priority>'+(index===0?'1.0':'0.7')+'</priority>\n'+
        '  </url>'
      ).join('\n')+
      '\n</urlset>\n';
  }

  async function buildStaticCopyZip(snapshot){
    snapshot=snapshot||{};
    const name=(snapshot&&snapshot.title)||'siteforge-static-copy';
    const project={name,version:'1.0.0',packageManager:'npm',files:[],assets:[]};
    const files={};
    const urlMap=(snapshot&&snapshot.assetUrlMap)||{};
    const metaTags=(snapshot&&snapshot.meta)||{};
    const description=metaTags['description']||metaTags['og:description']||'A website exported by SiteForge.';
    const ogImage=metaTags['og:image']||'';

    const fullHtml=String((snapshot&&snapshot.fullHtml)||'');
    const rootBody=extractBodySection(fullHtml);
    const rootBodyHtml=rewriteAssetUrls(stripDangerousHtml(rootBody.bodyHtml),urlMap);
    const rootBodyClass=(snapshot&&snapshot.bodyClass)||rootBody.bodyClass||'';
    const rootLang=(snapshot&&snapshot.lang)||'en';

    files['app/page.jsx']=buildPageModule({
      title:name,
      html:rootBodyHtml,
      bodyClass:rootBodyClass
    });

    const crawledPages=Array.isArray(snapshot.pages)?snapshot.pages:[];
    const seenRoutes=new Set(['']);
    const routeEntries=[];
    const pageRoutes=[{route:'',url:(snapshot&&snapshot.url)||'/',title:name}];

    crawledPages.forEach((page,index)=>{
      const route=routePathFromUrl(page&&page.url,index);
      if(!route||seenRoutes.has(route))return;
      seenRoutes.add(route);
      const pageBody=extractBodySection(String(page&&page.html||''));
      const pageHtml=rewriteAssetUrls(stripDangerousHtml(pageBody.bodyHtml),urlMap);
      routeEntries.push({
        route,
        url:page.url||'',
        title:page.title||route.split('/').pop()||'Page',
        html:pageHtml,
        bodyClass:page.bodyClass||pageBody.bodyClass||''
      });
      pageRoutes.push({route,url:page.url||'',title:page.title||route});
    });

    routeEntries.forEach(page=>{
      files['app/'+page.route+'/page.jsx']=buildPageModule(page);
    });

    const globalsParts=[];
    globalsParts.push('@tailwind base;','@tailwind components;','@tailwind utilities;','');
    globalsParts.push('.siteforge-original, .siteforge-page { min-height: 100vh; }');
    files['app/globals.css']=globalsParts.join('\n');

    const legacyParts=[];
    const inline=(snapshot&&snapshot.inlineStyles)||'';
    if(inline){
      legacyParts.push('/* Inline styles from source page */');
      let cssText=stripDangerousHtml(inline);
      cssText=rewriteAssetUrls(cssText,urlMap);
      legacyParts.push(cssText);
    }
    const external=(snapshot&&snapshot.externalStyles)||{};
    Object.keys(external).forEach(nameKey=>{
      const css=external[nameKey];
      if(css){
        legacyParts.push('/* '+nameKey+' */');
        let cssText=stripDangerousHtml(css);
        cssText=rewriteAssetUrls(cssText,urlMap);
        legacyParts.push(cssText);
      }
    });
    if(legacyParts.length)files['public/legacy.css']=legacyParts.join('\n');

    files['app/layout.jsx']=buildLayoutModule({
      title:name,
      lang:rootLang,
      bodyClass:rootBodyClass,
      meta:{description, 'og:description':description, 'og:image':ogImage}
    });

    files['public/sitemap.xml']=buildSitemap(pageRoutes.map(page=>page.route));
    files['public/robots.txt']='User-agent: *\n'+
      'Allow: /\n'+
      'Sitemap: https://yourdomain.com/sitemap.xml\n';

    if(routeEntries.length){
      files['PAGES.md']=buildRouteGuide(pageRoutes);
    }

    const components=extractComponents(fullHtml);
    const componentsDocs='# Component Guide\n\n'+
      'This page was analyzed and the following reusable components were detected:\n\n'+
      Object.entries(components).map(([name,info])=>
        '## '+name+'\n\n'+
        '- **Found**: '+info.count+' instance(s)\n'+
        '- **Selector**: `'+info.selector+'`\n'+
        '- **Sample HTML**:\n```html\n'+info.sample+'\n```\n'
      ).join('\n')+
      '\n## How to Use\n\n'+
      'You can extract these patterns into reusable React components in `app/components/`:\n\n'+
      '```jsx\n'+
      '// app/components/Header.jsx\n'+
      'export default function Header() {\n'+
      '  return (\n'+
      '    <header>\n'+
      '      {/* Your header content here */}\n'+
      '    </header>\n'+
      '  );\n'+
      '}\n'+
      '```\n';
    files['COMPONENTS.md']=componentsDocs;

    const assetMap=(snapshot&&snapshot.assets)||{};
    const assets=[];
    Object.keys(assetMap).forEach(fileName=>{
      const uri=assetMap[fileName];
      if(typeof uri==='string'&&uri.startsWith('data:')){
        assets.push({path:'public/'+fileName,dataUri:uri});
      }
    });
    project.assets=assets;

    Object.keys(files).forEach(p=>{project.files.push({path:p,content:files[p]});});
    const blob=await buildProjectZip(project);
    return{blob,project};
  }

  self.SiteForgeBuilder={buildProjectZip,buildStaticCopyZip};
})();
